# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3204da032df0897d4ba76a78d42880db2a452fd76aa1106e4e97091e694cbb19fd7eb5baa1e4fd9df395d5869a9bb8e27151cb476b927325d2ce167947591790

test:
  secret_key_base: 63ec9425724285f91999c53c7e71197c16e9c05b13696585fff231f3d34a542b9e408f14f07d261713a1e97a00bb940f778089066f9e4a648dfa4331e162f1bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
